spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pidev?useSSL=false&serverTimezone=UTC
    username: root
    password:  # Remove your actual password here
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmeeeedghoul@gmail.com  # Your Gmail address (ensure you don't hardcode your password here)
    password:  # Remove your Gmail password here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: <REPLACE_WITH_JWT_SECRET_KEY>  # Replace with a secret stored securely (e.g., environment variable)
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json

infobip:
  api:
    url: "https://ypjy3d.api.infobip.com"
    key: <REPLACE_WITH_INFIBO_API_KEY>  # Replace with your Infobip API key, stored securely
  sender: <REPLACE_WITH_INFIBO_SENDER>  # Replace with your Infobip sender phone number

twilio:
  account_sid: "<REPLACE_WITH_TWILIO_ACCOUNT_SID>"
  auth_token: "<REPLACE_WITH_TWILIO_AUTH_TOKEN>"
  phone_number: "<REPLACE_WITH_TWILIO_PHONE_NUMBER>"

admin:
  phone_number: "<REPLACE_WITH_ADMIN_PHONE_NUMBER>"  # Replace with your Admin's phone number (include country code)

sendinblue:
  api:
    key: <REPLACE_WITH_SENDINBLUE_API_KEY>  # Replace with your Sendinblue API key, stored securely
