spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Pidev?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmeeeedghoul@gmail.com  # Your Gmail address
    password: zxox gwnw olhi xyyk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

signature:
  image:
    path=/path/to/your/signature:
      png:
application:
  security:
    jwt:
      secret-key: JhtwZb0eG1auJ8fIuS7RlmStvl1jE5P0He7Fmj9T2Nl8dpG7gY3Uw5wKNvhfVojE5+lg4E28Q14e/pVX9hrp+Jq1kg+dfy6ixtP6tMzYhwpw6KjDC5FS9J7TO9Twsf7I
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088
  servlet:
    context-path: /api/v1/

springdoc:
  default-produces-media-type: application/json
infobip:
  api:
    url: "https://ypjy3d.api.infobip.com"
    key: "73d085fc07746e1908851f3f997c844d-ac649f8a-0dfb-448f-b5c7-d2d355b7b376"
  sender: "447491163443"


